### ISSUE TITLE
Vacation Lighting Director is unreliable

### ISSUE THREAD

**Issue by chetstone** [tslagle13/SmartThings#27]
I can't seem to get this smartapp to run for more than a day or two without quitting. I think the basic issue is that it uses runIn() to reschedule the next run every time it runs. According to the [Smartthings docs](http://docs.smartthings.com/en/latest/smartapp-developers-guide/scheduling.html) this practice is not recommended because if for some reason a run does not succeed, the rescheduling for the next run does not happen and the app is essentially dead. (At least until the mode is toggled again.) I think the way to fix this is to use schedule() to run the app every day at the programmed start time. That could also fail, but the next day it will try again and likely succeed. 

Maybe it's just me, but I have found the current implementation which starts the app based on a mode change to be unintuitive. When I think of a vacation lighting program, I would expect it to start in the early evening, then check to see if the mode is correct. I've found it so unintuitive that I've had to study the code closely in order to get it to work at all. For example, in the current implementation, the app won't run when first installed if you're already in the selected (let's say 'Away') mode. You have to change to a different mode, then back to 'Away' to get it to fire up and start checking the time and other parameters.

So I recommend changing the implementation to use schedule() as the primary trigger to start the app at a certain time every day, then check other states such as mode and day of the week to determine whether to switch lights on and off or not.

A workaround I came up with on a recent long vacation where I had enough time to study the issue (but no facility to program) was to use other smartthings facilities to do a mode change to 'Home' then back to 'Away' every day just before the starting time of the Director. But this is unsatisfactory because when I got home I had to remove this program and would have to reprogram it before the next vacation.

**Comment by tslagle13** [comment]
This method run reliability without fail for me daily.  The schedule method can work but it also vey "static".  It schedules based off the mode so it does not run alllll day until the mode is correct.  Less stress on the platform.  If you wish to have it run a specific way you may use the open source code to make it to your liking.

**Comment by chetstone** [comment]
I've decided to install `Hello, Home Phrase Director` which changes modes twice a day whether you're home or away. I think this should be an adequate workaround. But anyone trying to make `Vacation Lighting Director` work with the standard SmartThings modes (which only has one `Away` mode) will probably run into the issue I have described.

**Comment by tslagle13** [comment]
Agreed, you input is always valuable too :).  I have since added a paragraph to each section describing what each section is for as well as that I recommend using the app with two away modes.
